import json
import time
from core.log import setup_logger

logger = setup_logger(__name__)


def generate_report(findings, target, scan_type='scan'):
    report = {
        'target': target,
        'scan_type': scan_type,
        'timestamp': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'tool': 'XSStrike v3.1.5+',
        'summary': {
            'total_findings': len(findings),
            'critical': sum(1 for f in findings if f.get('severity') == 'critical'),
            'high': sum(1 for f in findings if f.get('severity') == 'high'),
            'medium': sum(1 for f in findings if f.get('severity') == 'medium'),
            'low': sum(1 for f in findings if f.get('severity') == 'low'),
        },
        'findings': findings,
    }
    return report


def save_json(report, path):
    with open(path, 'w') as f:
        json.dump(report, f, indent=2)


def save_html(report, path):
    rows = ''
    for f in report['findings']:
        severity = f.get('severity', 'info')
        sev_class = severity
        payload = f.get('payload', f.get('snippet', ''))
        rows += f'''<tr class="{sev_class}">
            <td>{f.get('type', 'unknown')}</td>
            <td>{f.get('parameter', 'N/A')}</td>
            <td>{severity}</td>
            <td><code>{payload}</code></td>
            <td>{f.get('confidence', 'N/A')}</td>
        </tr>\n'''
    summary = report['summary']
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>XSStrike Report — {report['target']}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
  h1 {{ color: #58a6ff; }}
  .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
  .summary div {{ background: #161b22; padding: 15px; border-radius: 8px; min-width: 100px; text-align: center; }}
  .summary .num {{ font-size: 28px; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #30363d; }}
  th {{ background: #161b22; }}
  .critical {{ background: #3d0000; }}
  .high {{ background: #3d1f00; }}
  .medium {{ background: #3d2e00; }}
  .low {{ background: #0d2818; }}
  code {{ background: #161b22; padding: 2px 6px; border-radius: 4px; font-size: 12px; word-break: break-all; }}
</style>
</head>
<body>
  <h1>XSStrike Security Report</h1>
  <p>Target: <strong>{report['target']}</strong> | Scan: {report['scan_type']} | {report['timestamp']}</p>
  <div class="summary">
    <div><span class="num">{summary['total_findings']}</span><br>Total</div>
    <div style="border-left: 3px solid #f85149;"><span class="num">{summary['critical']}</span><br>Critical</div>
    <div style="border-left: 3px solid #d29922;"><span class="num">{summary['high']}</span><br>High</div>
    <div style="border-left: 3px solid #d29922;"><span class="num">{summary['medium']}</span><br>Medium</div>
    <div style="border-left: 3px solid #3fb950;"><span class="num">{summary['low']}</span><br>Low</div>
  </div>
  <table>
    <tr><th>Type</th><th>Parameter</th><th>Severity</th><th>Payload / Details</th><th>Confidence</th></tr>
    {rows}
  </table>
  <p style="margin-top: 30px; font-size: 12px; color: #8b949e;">Generated by XSStrike at {report['timestamp']}</p>
</body>
</html>'''
    with open(path, 'w') as f:
        f.write(html)
